server:
  port: 8080
spring:
  profiles:
    active: "dev"
  datasource:
    username: "abc"
    password: "123456"
    url: "jdbc:mysql://beizidream.ddns.net:3306/abc?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false"
#  data:
#    redis:
#      host: "127.0.0.1"
#      port: 6379
#      password:
#      timeout: 5000
mybatis-plus:
  global-config:
    banner: false
  mapper-locations: classpath:mapper/*.xml
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl